# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieInfoTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieInfoTest
  pod "Moya/RxSwift", "~> 13.0"
  pod "RxCocoa", "~> 4.5.0"
  pod "Kingfisher", "~> 5.0"
  pod "IQKeyboardManagerSwift", "~> 6.5.0"
end
